### PR TITLE
Demo UI

### LINKED ISSUE #7: Create Demo UI
Create a UI to test the model in production.
The UI should be build using the steamlit package.

### PR DESCRIPTION
**Pull request by igorccouto**
Simple streamlit app to test the model

### CODE REVIEW

**Review by renanmouraf — CHANGES_REQUESTED** [review]
create a local specific README.md on how to use app.py

**Review by renanmouraf — CHANGES_REQUESTED** [review]
Change the path of the file from absolute to relative path

**Review by cpatrickalves — COMMENTED** [review]
I think we could save the app in "src/web/app.py" or "src/SOMEFOLDER/app.py"

**Comment by cpatrickalves** [comment]
@igorccouto creates a new PR.

**Pull request closed without merging**
